Repository Yudai-Saito/Homete, pull requests merged in 2021-12, with the labels that each got.

#3 vue.js用のDocker開発環境の用意
  frontend/Dockerfile
  frontend/docker-compose.yml
Labels: enhancement

#4 バックエンドのDocker開発環境の用意
  backend/.gitignore
  backend/Dockerfile
  backend/docker-compose.yml
Labels: enhancement

#12 コンテナ内でgitを使えるようにした
  backend/Dockerfile
  backend/docker-compose.yml
  frontend/Dockerfile
  frontend/docker-compose.yml
Labels: bug

#13 Vueプロジェクトを立ち上げた
  frontend/.gitignore
  frontend/README.md
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/assets/logo.png
  frontend/src/assets/logo.svg
  frontend/src/components/HelloWorld.vue
  frontend/src/main.js
  frontend/src/plugins/vuetify.js
  frontend/src/router/index.js
  frontend/src/views/About.vue
  frontend/src/views/Home.vue
  frontend/vue.config.js
Labels: enhancement

#15 flask環境の構築
  backend/requirements.txt
Labels: enhancement

#16 ログインページを作った
  frontend/src/App.vue
  frontend/src/router/index.js
  frontend/src/views/Login.vue
Labels: enhancement

#22 DBのモデル作成とマイグレーション
  backend/.gitignore
  backend/app/app.py
  backend/docker-compose.yml
  backend/migrations/README
  backend/migrations/alembic.ini
  backend/migrations/env.py
  backend/migrations/script.py.mako
  backend/migrations/versions/39c3a7528bf0_.py
  backend/models/models.py
  backend/requirements.txt
  backend/run.py
Labels: enhancement

#23 新規登録画面を作成した
  frontend/src/router/index.js
  frontend/src/views/Signup.vue
Labels: enhancement

#25 ログイン画面のアイコンを修正した。
  frontend/src/views/Login.vue
Labels: invalid

#28 メール認証用APIの作成
  backend/app/app.py
  backend/docker-compose.yml
  backend/requirements.txt
  backend/route/user.py
Labels: enhancement

#30 メール認証用のトークン生成とメール送信API
  backend/app/app.py
  backend/docker-compose.yml
  backend/requirements.txt
  backend/route/token.py
  backend/route/user.py
Labels: enhancement

#31 新規登録画面のテンプレートを変更した
  frontend/src/router/index.js
  frontend/src/views/Signup.vue
  frontend/src/views/Signup_reqmail.vue
Labels: bug

#34 AxiosのベースURLを設定
  frontend/.gitignore
  frontend/docker-compose.yml
  frontend/src/main.js
Labels: enhancement

#36 新規登録の情報をDBに格納するAPIを作った
  backend/app/app.py
  backend/models/models.py
  backend/requirements.txt
  backend/route/user.py
Labels: enhancement

#40 新規登録時に要求するメールアドレスをサーバーにPOSTする処理を追加した
  frontend/src/components/Requestmail.vue
  frontend/src/main.js
  frontend/src/views/Signup_reqmail.vue
Labels: enhancement

#52 ログイン用APIの実装
  backend/route/token.py
  backend/route/user.py
Labels: enhancement, backend

#54 パスワード確認用のフォームを削除して、新規登録用の情報をPOSTできるようにした
  frontend/src/views/Signup.vue
Labels: enhancement

#55 パスワード再設定メール送信とAPI
  backend/route/user.py
Labels: enhancement, backend

#56 メール送信完了の表示処理の整理と表示メッセージの統一
  frontend/src/components/Requestmail.vue
  frontend/src/views/Passreset_reqmail.vue
  frontend/src/views/Signup_reqmail.vue
Labels: enhancement

#57 ハッシュ化した再設定用パスワードを POST
  frontend/src/views/Passreset.vue
Labels: enhancement

#62 新規登録画面のバリデーション
  frontend/src/components/Requestmail.vue
  frontend/src/views/Signup.vue
  frontend/src/views/Signup_reqmail.vue
Labels: enhancement

#63 投稿受け付け用APIの実装
  backend/app/app.py
  backend/route/post.py
Labels: enhancement

#65 DBの更新とクエリストリングのセット
  backend/migrations/versions/a86ea50054db_.py
  backend/models/models.py
  backend/route/user.py
Labels: enhancement, backend

#64 パスワード再設定画面のバリデーション
  frontend/src/views/Passreset.vue
  frontend/src/views/Passreset_reqmail.vue
Labels: enhancement, frontend

#69 命名規則まとめを参考に統一
  frontend/src/router/index.js
  frontend/src/views/Login.vue
  frontend/src/views/Passreset.vue
  frontend/src/views/PassresetReqmail.vue
  frontend/src/views/Signup.vue
  frontend/src/views/SignupReqmail.vue
Labels: enhancement, frontend

#71 ユーザ認証をRedisに変更
  backend/app/app.py
  backend/docker-compose.yml
  backend/requirements.txt
  backend/route/post.py
  backend/route/token.py
  backend/route/user.py
Labels: documentation, backend

#72 PostgreSQLからMySQLへ移行
  backend/app/app.py
  backend/docker-compose.yml
  backend/migrations/versions/a86ea50054db_.py
  backend/migrations/versions/b0d8071fe30c_.py
  backend/models/models.py
  backend/requirements.txt
Labels: bug, backend

#73 リアクションの追加・削除のAPI
  backend/route/post.py
Labels: enhancement, backend

#75 componentsに投稿用のフォームを作った
  frontend/src/components/HelloWorld.vue
  frontend/src/components/PostHomete.vue
  frontend/src/components/Requestmail.vue
  frontend/src/views/Home.vue
  frontend/src/views/Login.vue
Labels: enhancement, frontend

#76 TOP画面に表示する投稿のテンプレート
  frontend/src/components/DisplayHomete.vue
  frontend/src/components/ReactionButton.vue
  frontend/src/components/RequestMail.vue
  frontend/src/views/Home.vue
Labels: enhancement, frontend

#77 投稿取得用APIの実装
  backend/app/app.py
  backend/models/models.py
  backend/requirements.txt
  backend/route/post.py
Labels: enhancement, backend

#78 ログイン画面のバリデーション
  frontend/src/views/Login.vue
Labels: enhancement, frontend

#82 ユーザログイン機能の実装
  backend/route/user.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/Login.vue
Labels: enhancement, frontend

#83 投稿画面のバリデーション
  frontend/src/components/PostHomete.vue
Labels: enhancement, frontend

#84 TOP画面のテンプレートを作成
  frontend/src/components/PostHomete.vue
  frontend/src/components/SideMenu.vue
  frontend/src/router/index.js
  frontend/src/views/Home.vue
  frontend/src/views/Top.vue
Labels: enhancement, frontend

#86 パスワード再設定と新規登録の際の完了を通知する画面の作成
  frontend/src/views/Login.vue
  frontend/src/views/Passreset.vue
  frontend/src/views/PassresetReqmail.vue
  frontend/src/views/Signup.vue
Labels: enhancement, frontend

#89 TOPの投稿一覧の表示だけ作成
  frontend/src/components/DisplayHomete.vue
  frontend/src/components/ReactionButton.vue
  frontend/src/views/Top.vue
Labels: enhancement, frontend
